// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#pragma once

#include <string>
#include <tuple>
#include <unordered_map>

#include <dstorage_etw.h>
#include <DxTimingCaptureLibrary/EtwCallbacks.h>
#include <DxTimingCaptureLibrary/DxTimingCaptureEventHandler.h> // TimestampConverter

namespace DirectX::Etw
{

// Decodes and correlates the DirectStorage ETW provider's events and reports the
// result through DirectStorageCallbacks. This is the DirectStorage counterpart to the
// D3D12/DXGK/PIX decoding in DxTimingCaptureProcessor: it owns the enqueue -> completion
// correlation and hands the consumer fully-formed operations. DxTimingCaptureProcessor composes
// one of these and the shared DirectX::Etw::EtwDispatcher routes DirectStorage events
// to it, so a single handler decodes D3D12/DXGK/PIX and DirectStorage together.
//
// The handler methods below are named OnTrace<Event> to match the emitting runtime
// function, as required by the EtwDispatcher's DirectStorage dispatch.
class DirectStorageProcessor
{
    DirectStorageCallbacks* m_callbacks;
    const TimestampConverter* m_timestampConverter;

    uint16_t m_nextFileId;
    std::unordered_map<uint64_t, uint16_t> m_fileIds;

    uint16_t m_nextQueueId;
    std::unordered_map<uint64_t, uint16_t> m_queueIds;

    std::unordered_map<uint64_t, DirectStorageCallbacks::ReadRequest> m_requests;

    using LookupKey = std::tuple<uint64_t, uint64_t>;
    struct LookupKeyHasher
    {
        size_t operator()(const std::tuple<uint64_t, uint64_t>& data) const
        {
            size_t h = ((uint64_t)(std::get<0>(data) << 32)) | std::get<1>(data);
            return h;
        }
    };

    struct LookupKeyComparer
    {
        bool operator()(const std::tuple<uint64_t, uint64_t>& left, const std::tuple<uint64_t, uint64_t>& right) const
        {
            return left == right;
        }
    };

    std::unordered_map<LookupKey, DirectStorageCallbacks::FenceSignal, LookupKeyHasher, LookupKeyComparer> m_fences;
    std::unordered_map<LookupKey, DirectStorageCallbacks::StatusNotification, LookupKeyHasher, LookupKeyComparer> m_statusArrays;
    std::unordered_map<LookupKey, DirectStorageCallbacks::SetEventNotification, LookupKeyHasher, LookupKeyComparer> m_handles;

    INT64 ToTimestamp(EVENT_RECORD* record) const
    {
        return m_timestampConverter->ConvertClockToTimeStamp(record->EventHeader.TimeStamp.QuadPart);
    }

public:
    // timestampConverter and callbacks are both required and are owned by the
    // enclosing DxTimingCaptureEventHandler for the lifetime of this processor.
    DirectStorageProcessor(DirectStorageCallbacks* callbacks, const TimestampConverter* timestampConverter)
        : m_callbacks(callbacks)
        , m_timestampConverter(timestampConverter)
        , m_nextFileId(1)
        , m_nextQueueId(1)
    {
        ThrowIf(callbacks == nullptr, E_INVALIDARG, L"DirectStorage callbacks are required and must not be null.");
        ThrowIf(timestampConverter == nullptr, E_INVALIDARG, L"timestampConverter is required and must not be null.");
    }

    void OnComplete()
    {
        // DirectStorage operations are reported as their completion events arrive;
        // enqueues still outstanding when the trace ends are intentionally dropped,
        // so there is nothing to flush here.
    }

    void UntrackFile(uint64_t file)
    {
        m_fileIds.erase(file);
    }

    uint16_t GetOrCreateFileId(uint64_t file, INT64 timestamp, std::wstring_view path = L"")
    {
        auto id = m_fileIds.find(file);
        if (id != m_fileIds.end())
        {
            return id->second;
        }

        m_nextFileId++;
        m_fileIds.insert(id, { file, m_nextFileId });

        // Register new files and ensure that if an empty path is specified an
        // autogenerated one is used based on the file id.
        std::wstring filePath(path);
        if (filePath.empty())
        {
            filePath = L"file# " + std::to_wstring(m_nextFileId);
        }

        ThrowFailure(m_callbacks->OnDirectStorageFile(m_nextFileId, timestamp, filePath));

        return m_nextFileId;
    }

    void OnTraceOpenFileEvent(EVENT_RECORD* record, DirectStorage::FileEventData data, std::wstring_view path)
    {
        GetOrCreateFileId(data.File, ToTimestamp(record), path);
    }

    void OnTraceCloseFileEvent(EVENT_RECORD* record, DirectStorage::FileEventData data)
    {
        UNREFERENCED_PARAMETER(record);
        UntrackFile(data.File);
    }

    void UntrackQueue(uint64_t queue)
    {
        m_queueIds.erase(queue);
    }

    uint16_t QueueToQueueId(uint64_t queue, INT64 timestamp, std::string_view name = "")
    {
        auto id = m_queueIds.find(queue);
        if (id != m_queueIds.end())
        {
            return id->second;
        }

        m_nextQueueId++;
        m_queueIds.insert(id, { queue, m_nextQueueId });

        ThrowFailure(m_callbacks->OnDirectStorageQueue(m_nextQueueId, timestamp, name));

        return m_nextQueueId;
    }

    void OnTraceCreateQueueEvent(
        EVENT_RECORD* record,
        DirectStorage::CreateQueueEventData data,
        std::string_view name)
    {
        QueueToQueueId(data.Queue, ToTimestamp(record), name);
    }

    void OnTraceCloseQueueEvent(EVENT_RECORD* record, DirectStorage::CloseQueueEventData data)
    {
        UNREFERENCED_PARAMETER(record);
        UntrackQueue(data.Queue);
    }

    void TrackRequest(uint64_t request, DirectStorageCallbacks::ReadRequest data)
    {
        m_requests[request] = data;
    }

    // DS 1.0 handler (Version 1) - no extended data
    void OnTraceEnqueueRequestEvent(
        EVENT_RECORD* record,
        DirectStorage::EnqueueRequestEventData data,
        std::string_view name)
    {
        // Call the DS 1.4 handler with default extended data.
        DirectStorage::EnqueueRequestEventExtendedData defaultExtended{};
        defaultExtended.TransformType = 0;
        OnTraceEnqueueRequestEvent(record, data, name, defaultExtended);
    }

    // DS 1.4 handler (Version 2) - with extended data
    void OnTraceEnqueueRequestEvent(
        EVENT_RECORD* record,
        DirectStorage::EnqueueRequestEventData data,
        std::string_view name,
        DirectStorage::EnqueueRequestEventExtendedData extendedData)
    {
        UNREFERENCED_PARAMETER(name);

        DirectStorageCallbacks::ReadRequest request{};
        request.EnqueueTimestamp = ToTimestamp(record);
        request.CompletionTimestamp = 0; // not completed
        request.EnqueueThreadId = record->EventHeader.ThreadId;
        request.QueueId = QueueToQueueId(data.Queue, request.EnqueueTimestamp);
        request.FileId = GetOrCreateFileId(data.File, request.EnqueueTimestamp);
        request.Offset = data.Offset;
        request.Size = data.SourceSize;
        request.CompressionType = data.CompressionFormat;
        request.ShuffleType = extendedData.TransformType;

        TrackRequest(data.Request, request);
    }

    void OnTraceRequestCompletedEvent(EVENT_RECORD* record, DirectStorage::RequestCompletedEventData data)
    {
        // Only report a read whose enqueue we actually saw. A completion whose enqueue
        // predates the trace has no request data to report, so it is dropped rather than
        // surfaced as an all-zero read on queue/file 0.
        auto entry = m_requests.find(data.Request);
        if (entry == m_requests.end())
        {
            return;
        }

        entry->second.CompletionTimestamp = ToTimestamp(record);
        ThrowFailure(m_callbacks->OnDirectStorageReadRequest(entry->second));

        // A request completes exactly once and nothing else reads m_requests, so drop it
        // here to bound memory -- same as the status/fence/set-event handlers.
        m_requests.erase(entry);
    }

    void TrackStatusArray(uint64_t statusArray, DirectStorageCallbacks::StatusNotification data)
    {
        m_statusArrays[std::make_tuple(statusArray, data.Index)] = data;
    }

    void OnTraceEnqueueStatusEvent(EVENT_RECORD* record, DirectStorage::EnqueueStatusEventData data)
    {
        DirectStorageCallbacks::StatusNotification status{};
        status.EnqueueTimestamp = ToTimestamp(record);
        status.CompletionTimestamp = 0; // not completed
        status.EnqueueThreadId = record->EventHeader.ThreadId;
        status.QueueId = QueueToQueueId(data.Queue, status.EnqueueTimestamp);
        status.StatusArray = data.StatusArray;
        status.Index = data.Index;

        TrackStatusArray(data.StatusArray, status);
    }

    void OnTraceStatusCompletedEvent(
        EVENT_RECORD* record,
        DirectStorage::StatusCompletedEventData data)
    {
        auto key = std::make_tuple(data.StatusArray, static_cast<uint64_t>(data.Index));
        auto entry = m_statusArrays.find(key);

        if (entry != m_statusArrays.end())
        {
            entry->second.CompletionTimestamp = ToTimestamp(record);
            ThrowFailure(m_callbacks->OnDirectStorageStatus(entry->second));
            m_statusArrays.erase(entry);
        }
        else
        {
            DirectStorageCallbacks::StatusNotification status{};
            status.EnqueueTimestamp = ToTimestamp(record);
            status.CompletionTimestamp = status.EnqueueTimestamp;
            status.EnqueueThreadId = record->EventHeader.ThreadId;
            status.QueueId = QueueToQueueId(data.Queue, status.EnqueueTimestamp);
            status.StatusArray = data.StatusArray;
            status.Index = data.Index;

            ThrowFailure(m_callbacks->OnDirectStorageStatus(status));
        }
    }

    void TrackFence(uint64_t fence, DirectStorageCallbacks::FenceSignal data)
    {
        m_fences[std::make_tuple(fence, data.Value)] = data;
    }

    void TrackSetEvent(uint64_t handle, DirectStorageCallbacks::SetEventNotification data)
    {
        m_handles[std::make_tuple(handle, static_cast<uint64_t>(0))] = data;
    }

    void OnTraceEnqueueSignalEvent(EVENT_RECORD* record, DirectStorage::SignalEventData data)
    {
        DirectStorageCallbacks::FenceSignal signal{};
        signal.EnqueueTimestamp = ToTimestamp(record);
        signal.CompletionTimestamp = 0; // not completed
        signal.EnqueueThreadId = record->EventHeader.ThreadId;
        signal.QueueId = QueueToQueueId(data.Queue, signal.EnqueueTimestamp);
        signal.Fence = data.Fence;
        signal.Value = data.Value;

        TrackFence(data.Fence, signal);
    }

    void OnTraceSignalCompletedEvent(EVENT_RECORD* record, DirectStorage::SignalEventData data)
    {
        auto key = std::make_tuple(data.Fence, data.Value);
        auto entry = m_fences.find(key);

        if (entry != m_fences.end())
        {
            entry->second.CompletionTimestamp = ToTimestamp(record);
            ThrowFailure(m_callbacks->OnDirectStorageFenceSignal(entry->second));
            m_fences.erase(entry);
        }
        else
        {
            DirectStorageCallbacks::FenceSignal signal{};
            signal.EnqueueTimestamp = ToTimestamp(record);
            signal.CompletionTimestamp = signal.EnqueueTimestamp;
            signal.EnqueueThreadId = record->EventHeader.ThreadId;
            signal.QueueId = QueueToQueueId(data.Queue, signal.EnqueueTimestamp);
            signal.Fence = data.Fence;
            signal.Value = data.Value;

            ThrowFailure(m_callbacks->OnDirectStorageFenceSignal(signal));
        }
    }

    void OnTraceSubmitEvent(EVENT_RECORD* record, DirectStorage::SubmitEventData data)
    {
        DirectStorageCallbacks::Submit submit{};
        submit.Timestamp = ToTimestamp(record);
        submit.QueueId = QueueToQueueId(data.Queue, submit.Timestamp);
        submit.AutoSubmitted = data.IsAutoSubmit != 0;
        submit.EnqueueThreadId = record->EventHeader.ThreadId;

        ThrowFailure(m_callbacks->OnDirectStorageSubmit(submit));
    }

    void OnTraceEnqueueSetEvent(EVENT_RECORD* record, DirectStorage::SetEventData data)
    {
        DirectStorageCallbacks::SetEventNotification setEvent{};
        setEvent.EnqueueTimestamp = ToTimestamp(record);
        setEvent.CompletionTimestamp = 0; // not completed
        setEvent.EnqueueThreadId = record->EventHeader.ThreadId;
        setEvent.QueueId = QueueToQueueId(data.Queue, setEvent.EnqueueTimestamp);
        setEvent.Handle = data.Handle;

        TrackSetEvent(data.Handle, setEvent);
    }

    void OnTraceSetEventCompletedEvent(EVENT_RECORD* record, DirectStorage::SetEventData data)
    {
        auto key = std::make_tuple(data.Handle, static_cast<uint64_t>(0));
        auto entry = m_handles.find(key);

        if (entry != m_handles.end())
        {
            entry->second.CompletionTimestamp = ToTimestamp(record);
            ThrowFailure(m_callbacks->OnDirectStorageSetEvent(entry->second));
            m_handles.erase(entry);
        }
        else
        {
            DirectStorageCallbacks::SetEventNotification setEvent{};
            setEvent.EnqueueTimestamp = ToTimestamp(record);
            setEvent.CompletionTimestamp = setEvent.EnqueueTimestamp;
            setEvent.EnqueueThreadId = record->EventHeader.ThreadId;
            setEvent.QueueId = QueueToQueueId(data.Queue, setEvent.EnqueueTimestamp);
            setEvent.Handle = data.Handle;

            ThrowFailure(m_callbacks->OnDirectStorageSetEvent(setEvent));
        }
    }
};

} // namespace DirectX::Etw